name: andres-ruda
services:
   andres-ruda:
     image: localhost:8082/andres-ruda:latest
     restart: always
     ports:
       - "8080:8080"
     environment:
      - API_KEY=/app/secrets/api_key 
      - AMBIENTE=Development
     secrets:
      - api_key
