pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            stages {
                stage('packages') {
                    steps {
                        sh 'npm install'
                    }
                }
                stage('build') {
                    steps {
                        sh 'npm run build'
                    }
                }
                stage('test') {
                    steps {
                        sh 'npm test'
                    }
                }
                //stage('run'){
                //    steps {
                //        sh 'node dist/index.js'
                //    }
                //}
            }
        }
    }
}
